apiVersion: v1
kind: Service
metadata:
  name: springboot-configmap
spec:
  type: NodePort
  selector:
    app: springboot-configmap
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001